def get_components(): 
    c1 = "Navigation"
    c2 = "Guidiance"
    c3 = "Cooling"
    c4 = "Heater"
    c5 = "Computer"
    c6 = "Honeycomb"
    c7 = "Engine"
    c8 = "Thruster"
    c9 = "Communications"